# FontForgeを実行
$fontforge = "C:\Program Files (x86)\FontForgeBuilds\bin\ffpython.exe"
$inputDir = ".\2_transformed"
$scr = ".\1_scripts\scr_save_ttf.py"

& $fontforge $scr "$inputDir\BIZUDGothic_UltraCond-Regular.sfd" "Bi_Hanbun_Gothic" "Biはんぶんゴシック" "UC" "はんぶんゴシック"
& $fontforge $scr "$inputDir\BIZUDGothic_UltraCond-Bold.sfd" "Bi_Hanbun_Gothic" "Biはんぶんゴシック" "UC" "はんぶんゴシック"
& $fontforge $scr "$inputDir\BIZUDMincho_UltraCond-Regular.sfd" "Bi_Hanbunko_Mincho" "Biはんぶんこ明朝" "UC" "はんぶん明朝"
& $fontforge $scr "$inputDir\BIZUDMincho_UltraCond-Bold.sfd" "Bi_Hanbunko_Mincho" "Biはんぶんこ明朝" "UC" "はんぶん明朝"
& $fontforge $scr "$inputDir\BIZUDPGothic_UltraCond-Regular.sfd" "Bi_HanbunP_Gothic" "BiはんぶんPゴシック" "UC" "はんぶんゴシック"
& $fontforge $scr "$inputDir\BIZUDPGothic_UltraCond-Bold.sfd" "Bi_HanbunP_Gothic" "BiはんぶんPゴシック" "UC" "はんぶんゴシック"
& $fontforge $scr "$inputDir\BIZUDPMincho_UltraCond-Regular.sfd" "Bi_HanbunkoP_Mincho" "BiはんぶんこP明朝" "UC" "はんぶん明朝"
& $fontforge $scr "$inputDir\BIZUDPMincho_UltraCond-Bold.sfd" "Bi_HanbunkoP_Mincho" "BiはんぶんこP明朝" "UC" "はんぶん明朝"

& $fontforge $scr "$inputDir\BIZUDGothic_ExtraCond-Regular.sfd" "Bi_Waribiki_Gothic" "Biわりびきゴシック" "EC" "わりびきゴシック"
& $fontforge $scr "$inputDir\BIZUDGothic_ExtraCond-Bold.sfd" "Bi_Waribiki_Gothic" "Biわりびきゴシック" "EC" "わりびきゴシック"
& $fontforge $scr "$inputDir\BIZUDMincho_ExtraCond-Regular.sfd" "Bi_Waribiki_Mincho" "Biわりびき明朝" "EC" "わりびき明朝"
& $fontforge $scr "$inputDir\BIZUDMincho_ExtraCond-Bold.sfd" "Bi_Waribiki_Mincho" "Biわりびき明朝" "EC" "わりびき明朝"
& $fontforge $scr "$inputDir\BIZUDPGothic_ExtraCond-Regular.sfd" "Bi_WaribikiP_Gothic" "BiわりびきPゴシック" "EC" "わりびきゴシック"
& $fontforge $scr "$inputDir\BIZUDPGothic_ExtraCond-Bold.sfd" "Bi_WaribikiP_Gothic" "BiわりびきPゴシック" "EC" "わりびきゴシック"
& $fontforge $scr "$inputDir\BIZUDPMincho_ExtraCond-Regular.sfd" "Bi_WaribikiP_Mincho" "BiわりびきP明朝" "EC" "わりびき明朝"
& $fontforge $scr "$inputDir\BIZUDPMincho_ExtraCond-Bold.sfd" "Bi_WaribikiP_Mincho" "BiわりびきP明朝" "EC" "わりびき明朝"

& $fontforge $scr "$inputDir\BIZUDGothic_SemiCond-Regular.sfd" "Bi_Hosome_Gothic" "Biほそめゴシック" "SC" "ほそめゴシック"
& $fontforge $scr "$inputDir\BIZUDGothic_SemiCond-Bold.sfd" "Bi_Hosome_Gothic" "Biほそめゴシック" "SC" "ほそめゴシック"
& $fontforge $scr "$inputDir\BIZUDMincho_SemiCond-Regular.sfd" "Bi_Hosome_Mincho" "Biほそめ明朝" "SC" "ほそめ明朝"
& $fontforge $scr "$inputDir\BIZUDMincho_SemiCond-Bold.sfd" "Bi_Hosome_Mincho" "Biほそめ明朝" "SC" "ほそめ明朝"
& $fontforge $scr "$inputDir\BIZUDPGothic_SemiCond-Regular.sfd" "Bi_HosomeP_Gothic" "BiほそめPゴシック" "SC" "ほそめゴシック"
& $fontforge $scr "$inputDir\BIZUDPGothic_SemiCond-Bold.sfd" "Bi_HosomeP_Gothic" "BiほそめPゴシック" "SC" "ほそめゴシック"
& $fontforge $scr "$inputDir\BIZUDPMincho_SemiCond-Regular.sfd" "Bi_HosomeP_Mincho" "BiほそめP明朝" "SC" "ほそめ明朝"
& $fontforge $scr "$inputDir\BIZUDPMincho_SemiCond-Bold.sfd" "Bi_HosomeP_Mincho" "BiほそめP明朝" "SC" "ほそめ明朝"